# VIP Vision Inspection Pipeline - Tunable Parameters
# This file contains all configurable parameters for the detection models
# Modify these values to tune the detection performance

# Global pipeline parameters
global:
  confidence_threshold: 0.3  # Minimum confidence score for detections (0.0-1.0)
  min_bbox_size: 15  # Minimum bounding box size in pixels
  gaussian_blur_size: 5  # Standard Gaussian blur kernel size for noise reduction

# Scratch Detection Parameters
scratches:
  canny_low: 50  # Lower threshold for Canny edge detection
  canny_high: 150  # Upper threshold for Canny edge detection
  min_length: 20  # Minimum scratch length in pixels
  min_width: 2  # Minimum scratch width in pixels
  min_area: 50  # Minimum area for connected components
  min_aspect_ratio: 2.0  # Minimum aspect ratio for elongated features
  score_normalization: 10.0  # Normalization factor for score calculation

# Crack Detection Parameters
cracks:
  sobel_kernel: 3  # Kernel size for Sobel operators
  threshold: 50  # Threshold for crack detection
  min_length: 15  # Minimum crack length in pixels
  min_width: 1  # Minimum crack width in pixels
  min_area: 20  # Minimum area for crack detection
  min_aspect_ratio: 1.5  # Minimum aspect ratio for elongated features
  elongation_normalization: 8.0  # Normalization factor for elongation score
  gradient_normalization: 100.0  # Normalization factor for gradient score

# Contamination Detection Parameters
contamination:
  blur_size: 15  # Size of Gaussian blur for high-pass filter
  threshold: 30  # Threshold for contamination detection
  min_area: 100  # Minimum contamination area in pixels
  max_area: 10000  # Maximum contamination area in pixels
  area_normalization: 5000.0  # Normalization factor for area score
  contrast_normalization: 100.0  # Normalization factor for contrast score

# Discoloration Detection Parameters
discoloration:
  window_size: 21  # Size of local window for mean calculation
  threshold: 15.0  # Color difference threshold for detection
  min_area: 200  # Minimum discoloration area in pixels
  area_normalization: 10000.0  # Normalization factor for area score
  color_normalization: 50.0  # Normalization factor for color difference score

# Flash Detection Parameters
flash:
  brightness_threshold: 200  # Threshold for bright regions
  gradient_threshold: 30  # Threshold for gradient detection
  min_area: 150  # Minimum flash area in pixels
  sobel_kernel: 3  # Kernel size for Sobel operators
  area_normalization: 5000.0  # Normalization factor for area score
  brightness_normalization: 255.0  # Normalization factor for brightness score

# Morphological Operations Parameters
morphology:
  # Contamination detector
  contamination_kernel_size: 5  # Kernel size for morphological operations
  
  # Crack detector
  crack_horizontal_kernel: [1, 3]  # Horizontal kernel for crack detection
  crack_vertical_kernel: [3, 1]  # Vertical kernel for crack detection
  crack_close_kernel_size: 3  # Kernel size for closing operation
  
  # Scratch detector
  scratch_kernel_size: 3  # Kernel size for morphological operations
  
  # Flash detector
  flash_kernel_size: 5  # Kernel size for morphological operations
  
  # Discoloration detector
  discoloration_kernel_size: 7  # Kernel size for morphological operations
