# Custom Roboflow Plastic Defects Dataset Configuration  
name: "roboflow_plastic_defects"
description: "Custom plastic container defects dataset - 450 images, directly relevant to VIP"
task_type: "detection"

# Dataset paths
data_dir: "data/raw/roboflow_plastic_defects"
processed_dir: "data/processed/roboflow_plastic_defects"
manifest_file: "data/processed/roboflow_plastic_defects/manifest.jsonl"

# Annotation format
annotation_format: "coco"  # COCO JSON format

# Class labels (will be determined from COCO categories)
classes: []  # Will be auto-detected from COCO annotations

# Label mapping to VIP types (will be applied automatically)
label_map:
  "scratch": "scratch"
  "contamination": "contamination"
  "crack": "crack"
  "discoloration": "discoloration"
  "flash": "flash"
  # Add more mappings as needed based on your actual classes

# Dataset splits (use Roboflow's pre-defined splits)
splits:
  train: "train"      # Use train/ directory
  val: "valid"        # Use valid/ directory  
  test: "test"        # Use test/ directory

# License and attribution
license: "CC BY 4.0"
license_url: "https://creativecommons.org/licenses/by/4.0/"
citation: "Roboflow Plastic Defects Dataset. Available at: https://universe.roboflow.com/panops/plastic-defects"

# Source information
source_url: "https://universe.roboflow.com/panops/plastic-defects"
download_method: "manual"  # Requires Roboflow account

# Dataset statistics
stats:
  total_images: 149
  image_format: "jpg"
  image_size: "variable"
  annotation_format: "bounding_boxes"
  defect_classes: 3
  size_mb: 50

# Usage permissions
commercial_use: true
attribution_required: true
share_alike: false

# Relevance to VIP
vip_relevance: "high"  # Direct match for plastic container defects
defect_coverage:
  contamination: true
  scratches: true
  cracks: false
  discoloration: false
  flash: false

# Image preprocessing
preprocessing:
  resize_width: 640      # Standard for object detection
  normalize: true
  format: "jpg"
